/// This file is auto-generated by Scribble and shouldn't be edited directly.
/// Use --disarm prior to make any changes.
/// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

/// @title CapAccumulator
///  @notice Task 1.5 scribble target. A minimal accumulator carrying the SAME invariant
///          shape as RiskGuard's per-market cap, annotated in scribble's specification
///          language so the annotation compiles to a runtime assertion.
///  Why a separate small contract rather than annotating RiskGuard directly:
///  scribble rewrites the source it instruments. Pointing it at RiskGuard would produce an
///  instrumented copy competing with the deployed original, and the deployed bytecode is
///  what every onchain claim in this project rests on. A dedicated target proves the tool
///  works on our invariant shape without touching the contract that is already live and
///  already proven by halmos and hevm.
///  The invariant: total can never exceed cap. This is RiskGuard's `exposureOf[market] <=
///  maxPerMarket[market]` reduced to its smallest honest form.
contract CapAccumulator {
    struct vars1 {
        uint256 old_0;
    }

    uint256 public total;
    uint256 public immutable cap;

    constructor(uint256 _cap) {
        cap = _cap;
    }

    function add(uint256 amount) external {
        _original_CapAccumulator_add(amount);
        unchecked {
            if (!(total <= cap)) {
                emit __ScribbleUtilsLib__40.AssertionFailed("001447:0089:000 0: total never exceeds cap");
                assert(false);
            }
        }
    }

    function _original_CapAccumulator_add(uint256 amount) internal {
        total += amount;
    }

    function subtract(uint256 amount) external {
        vars1 memory _v;
        unchecked {
            _v.old_0 = total;
        }
        _original_CapAccumulator_subtract(amount);
        unchecked {
            if (!(total <= _v.old_0)) {
                emit __ScribbleUtilsLib__40.AssertionFailed("001962:0088:000 1: total never underflows");
                assert(false);
            }
        }
    }

    function _original_CapAccumulator_subtract(uint256 amount) internal {
        total -= amount;
    }
}

library __ScribbleUtilsLib__40 {
    event AssertionFailed(string message);

    event AssertionFailedData(int eventId, bytes encodingData);

    function assertionFailed(string memory arg_0) internal {
        emit AssertionFailed(arg_0);
    }

    function assertionFailedData(int arg_0, bytes memory arg_1) internal {
        emit AssertionFailedData(arg_0, arg_1);
    }

    function isInContract() internal returns (bool res) {
        assembly {
            res := sload(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c)
        }
    }

    function setInContract(bool v) internal {
        assembly {
            sstore(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c, v)
        }
    }
}