#!/usr/bin/env bash
set -uo pipefail
cd "$(dirname "$0")"
. ./lib.sh
D=$(date -u '+%Y-%m-%d')
CoE="$REPO/evidence/CHAIN-OF-EVIDENCE.md"

cat >> "$CoE" <<MD
| C-705 | Five symbolic theorems about the fee are proved by halmos 0.3.3 over all inputs in range, not sampled: the fee never exceeds the immutable ceiling, equals notional*bps/10000 exactly, is monotonic in notional, the rate can only ever fall, and totalCollected accumulates exactly with no counter increment for a zero-value charge. Each runs isolated with a wall-clock timeout so a solver stall is reported as a failure rather than as silence, and the declared-theorem count is asserted against the executed count so a zero-test run cannot read as green | evidence/phase7/fee-formal.txt, contracts/test/FeeFormal.t.sol | bash scripts/104b-fee-formal.sh | DEMONSTRATED | 7.4 | $D |
| C-706 | Six mutations of the fee logic, wrong divisor, ceiling check deleted, one-directional check deleted, event emitting notional in place of feeAmount, balance-delta check deleted and charger authorisation deleted, are each killed by a named test. A seventh mutation SURVIVED on the first run and was recorded as a finding rather than a score: the ceiling check inside setFeeBps was unreachable dead code, since the can-only-lower check already forces newBps < feeBps <= MAX_FEE_BPS by induction. It was deleted from the contract rather than covered by a test that could never reach it, and the invariant it expressed is now proved inductively by check_setFeeBpsCanOnlyLower | evidence/phase7/fee-mutation.txt | bash scripts/104-fee-mutation.sh | DEMONSTRATED | 7.5 | $D |
| C-707 | A real fee was charged on X Layer testnet in tx 0xd49391a1404815b742c7f6f25bce763bc18f77eebb8534835ef8785f1097a5c5, whose receipt carries a decoded FeeCharged log with feeAmount 100000000000000000 on a notional of 20000000000000000000 at 50 bps, decoded from eth_getTransactionReceipt and never from local state, and cross-checked against a treasury balance delta of exactly the same amount and chargeCount moving 1 to 2. The first run of this gate FAILED and was right to: the treasury was the deployer, who was also the maker, so 20e18 of trade proceeds and 0.1e18 of fee landed in one balance and revenue could not be stated from balances at all. A distinct treasury address was assigned before the gate passed | evidence/phase7/fee-live.txt | bash scripts/105-fee-live-testnet.sh | DEMONSTRATED | 7.6 | $D |
| C-708 | Fee revenue in the dashboard is read from chain and computed nowhere in the frontend. Totals come from FeeCollector.chargeCount() and totalCollected(), detail rows from decoded FeeCharged logs fetched under X Layer's 100-block eth_getLogs ceiling by a bounded backward scan with a persistent cursor, 106 windows cold and 3 warm. Three checks pass: a comment-and-string-stripping checker finds no arithmetic, accumulation or numeric coercion of any fee value across 18 frontend files and catches an injected feeA + feeB when self-tested; with the fee source removed the panel renders an error and no zero fallback exists on any fee field; and metrics.json total 200000000000000000 over 2 events equals both live contract state and the independent sum of the decoded logs | evidence/phase7/fee-metrics.txt, ui-v2/src/components/revenue-panel.tsx | bash scripts/107-fee-ui-gate.sh | DEMONSTRATED | 7.7 | $D |
| C-709 | Three separate places held deployment addresses as literals and all three were showing an abandoned deployment after the 7.6 redeploy: the metrics shell script, the metrics JSON writer, and the UI contract manifest. All now derive from deployments.json or from docs/verified/deployments.md, and the deploy script regenerates the UI manifest so the dashboard cannot render one deployment's addresses beside another's numbers | scripts/88-recompute-metrics.sh, scripts/recompute_metrics.py, scripts/12-deploy-venue.sh | bash scripts/12-deploy-venue.sh | DEMONSTRATED | 7.7 | $D |
MD

echo "rows now: $(grep -c '^| C-' "$CoE")"
