#!/usr/bin/env bash
set -uo pipefail
cd "$(dirname "$0")"
. ./lib.sh
D=$(date -u '+%Y-%m-%d')
CoE="$REPO/evidence/CHAIN-OF-EVIDENCE.md"

cat >> "$CoE" <<MD
| C-800 | The vault design was chosen against three reachable primary sources and TWO patterns were rejected with stated reasons: ERC-4626 share accounting, because shares price a pool and there is no pool, so a share price would either socialise one depositor's losses onto another and make per-user limits theatre, or duplicate the per-user accounting it sits on; and a withdrawal delay queue, because a delay is a timer and the DelayedWithdrawal finding shows how cheaply a third party resets one, and because a vault that answers "in 24 hours" has renamed custody rather than solved it | evidence/phase8/vault-research.md | bash scripts/111-vault-research.sh | DEMONSTRATED | 8.1 | $D |
| C-801 | AgentVault holds user capital the agent may trade and may never move out. The agent key, the owner key and an arbitrary key each fail to withdraw a depositor's balance, and the stronger claim is asserted too: every state-changing function is walked and none moves funds to a caller-named address, because openTrade sends only to an immutable tradeTarget fixed at construction. 18 of 18 tests pass including a fuzz over deposit and withdrawal exactness | evidence/phase8/vault-tests.txt, contracts/src/AgentVault.sol | bash scripts/112b-vault-tests.sh | DEMONSTRATED | 8.2 | $D |
| C-802 | Per-user limits are enforced in two independent places. Offchain, evaluate_for_user reports UserLimitExceeded naming the user's own limit rather than the system's, and prop_a_user_limit_can_never_widen_what_the_system_allows proves containment over arbitrary user limits and orders, with an anti-vacuity pair proving unbounded user limits change no verdict. Onchain, the same over-limit call was SUBMITTED to X Layer testnet and landed reverted with status 0x0 in block 38356671, while the within-limit counterfactual succeeded and committed exactly the limit | evidence/phase8/per-user-limits.txt | bash scripts/112d-per-user-limits.sh | DEMONSTRATED | 8.3 | $D |
| C-803 | Six symbolic custody theorems are proved by halmos over all inputs in range: a depositor can always withdraw in full whether paused or not, pause blocks every agent action, the agent can never exceed a depositor's limit, solvency holds across deposit and withdrawal, no caller but the depositor can withdraw quantified over every address, and the state the other five quantify over is genuinely constructible | evidence/phase8/vault-formal.txt, contracts/test/VaultFormal.t.sol | bash scripts/112e-vault-formal.sh | DEMONSTRATED | 8.4 | $D |
| C-804 | Seven vault mutations are each killed, including M7 which ADDS a pause check to the withdrawal path, the exact trap the research forbade. The gate runs every theorem against every mutant rather than one guessed theorem, and that change exposed a real vacuity: the depositor-can-always-withdraw theorem asserted what a successful withdrawal returns but never that it succeeds, so a reverting path was discarded by the solver and M1 survived all six theorems while four unit tests caught it. Every positive theorem now rules out the revert explicitly | evidence/phase8/vault-mutation.txt | bash scripts/112-vault-mutation.sh | DEMONSTRATED | 8.5 | $D |
| C-805 | A full deposit, agent action and withdrawal cycle ran live on X Layer testnet with three transactions at status 0x1. Custody was exact: 5 tQUOTE deposited, vault balance back to zero. The gate also reconciles all THREE addresses holding the token and asserts their deltas sum to zero, which is what caught the first run: a two-term wallet comparison showed a 2 tQUOTE loss that was neither loss nor dust but the agent funding closeTrade from its own wallet while the venue held what openTrade sent it | evidence/phase8/vault-live.txt | bash scripts/113-vault-live.sh | DEMONSTRATED | 8.6 | $D |
| C-806 | A pause landed MID-FLIGHT and is proven so by block numbers: openTrade at block 38358088 with 1 tQUOTE committed at the venue, setPaused at 38358109, a new agent action submitted at 38358126 landing reverted with status 0x0, closeTrade at 38358137, and the depositor withdrawing in full at 38358147 with paused still reading true and the vault balance ending at zero | evidence/phase8/pause-live.txt | bash scripts/114-pause-under-load.sh | DEMONSTRATED | 8.7 | $D |
| C-807 | Four attacks against the live deployed vault, run with the deployer key which is simultaneously the vault owner and the agent, all failed with decoded selectors: withdrawing one wei past the attacker's own balance returned InsufficientBalance, opening a trade one wei past the limit returned ExceedsUserLimit, unpausing another depositor is not expressible because paused is keyed on msg.sender with no override, and pausing to strand funds failed because withdrawAll returned status 0x1 with paused still true and the balance ending at zero | evidence/phase8/phase8-redteam.md | bash scripts/115-phase8-redteam.sh | DEMONSTRATED | 8.8 | $D |
MD

echo "rows now: $(grep -c '^| C-' "$CoE")"
