#!/usr/bin/env bash
# Task 9.3 gate: smart defaults, pre-selected and safe.
#
# THINKING: #29 margin-of-safety (a default is what most users will run, so it is the real limit),
# #33 Pareto, #12 design thinking.
#
# EVIDENCE PATH: evidence/phase9/defaults.md
# PASS: a user who touches nothing runs under limits identical to Limits::conservative,
# proven by reading the deployed vault state after activation.
#
# FAKE WIN, quoted: "defaults displayed in the UI that differ from what is written onchain."
# COUNTER, quoted: "the check reads the limits back from the vault and diffs them against the
# displayed values."
#
# THREE PLACES MUST AGREE, not two. The task names the UI and the chain; there is a third, and it is
# the one that rots quietly: the Rust crate. So the chain of equality checked here is
#
#     Limits::conservative  ==  data/limits.json  ==  AgentVault.maxNotional(user)
#
# and the middle term is GENERATED BY THE CRATE (cargo test export_conservative_defaults_for_the_ui)
# rather than typed into TypeScript, so the UI cannot drift from the engine at all.
set -uo pipefail
cd "$(dirname "$0")"
. ./lib.sh

OUT="$REPO/evidence/phase9/defaults.md"
mkdir -p "$(dirname "$OUT")"
RPC="$XLAYER_TESTNET_RPC"
J="$REPO/deployments.json"
a() { python3 -c "import json;print(json.load(open('$J'))['$1'])"; }
VAULT=$(a agentVault)

# 1. Regenerate limits.json FROM THE CRATE, so this gate cannot pass against a stale file.
cd "$REPO"
cargo test -p risk-engine export_conservative_defaults_for_the_ui 2>&1 | tail -3

{
echo "# Task 9.3: smart defaults, pre-selected and safe"
echo
echo "Run $(date -u '+%Y-%m-%d %H:%M:%S UTC')."
echo
echo "## The chain of equality this gate checks"
echo
echo '```'
echo "Limits::conservative  ==  ui-v2/public/data/limits.json  ==  AgentVault.maxNotional(user)"
echo "      (the Rust crate)              (what the screen renders)         (what is actually onchain)"
echo '```'
echo
echo "The task asks for two of these. The third, the crate, is included because it is the one that"
echo "rots quietly: a TypeScript constant holding 25 would let the engine change while the screen"
echo "kept saying 25. limits.json is WRITTEN BY the crate, so there is one definition."
echo
echo "## What the crate produced"
echo
echo '```json'
cat "$REPO/ui-v2/public/data/limits.json"
echo '```'
echo
} > "$OUT"

# 2. Read what the UI would display for the per-order limit, in wei.
DISPLAY_WEI=$(python3 -c "
import json
d = json.load(open('$REPO/ui-v2/public/data/limits.json'))
m = next(l for l in d['limits'] if l['key'] == 'maxOrderNotional')
print(m['micro'] * 10**12)
")

# 3. Read what is ACTUALLY onchain for this depositor.
ONCHAIN_WEI=$(cast call "$VAULT" "maxNotional(address)(uint256)" "$DEPLOYER_ADDRESS" --rpc-url "$RPC" | awk '{print $1}')
BAL=$(cast call "$VAULT" "balanceOf(address)(uint256)" "$DEPLOYER_ADDRESS" --rpc-url "$RPC" | awk '{print $1}')

{
echo "## Read back from the deployed vault"
echo
echo '```'
echo "vault:                       $VAULT"
echo "depositor:                   $DEPLOYER_ADDRESS"
echo "limits.json maxOrderNotional: $DISPLAY_WEI wei   (what the screen shows)"
echo "AgentVault.maxNotional:       $ONCHAIN_WEI wei   (what is enforced onchain)"
echo "AgentVault.balanceOf:         $BAL wei"
echo '```'
} >> "$OUT"

if [ "$DISPLAY_WEI" = "$ONCHAIN_WEI" ]; then
  VERDICT="PASS"
  {
    echo
    echo "The displayed default and the onchain limit are the SAME NUMBER. A user who touches nothing"
    echo "runs under exactly the limit the risk engine ships."
  } >> "$OUT"
else
  VERDICT="FAIL"
  {
    echo
    echo "MISMATCH. The screen would show $DISPLAY_WEI while the chain enforces $ONCHAIN_WEI."
    echo "This is the named fake win for this task, caught."
  } >> "$OUT"
fi

{
echo
echo "## GATE: $VERDICT"
} >> "$OUT"

tail -22 "$OUT"
[ "$VERDICT" = "PASS" ]
