#!/usr/bin/env bash
set -uo pipefail
cd "$(dirname "$0")"
. ./lib.sh
D=$(date -u '+%Y-%m-%d')
CoE="$REPO/evidence/CHAIN-OF-EVIDENCE.md"

cat >> "$CoE" <<MD
| C-900 | Connecting from a cold page reaches a real address and the real chain: the address is what eth_requestAccounts returned and the chain id is what eth_chainId returned from testrpc.xlayer.tech, both read back out of DOM data attributes the component wrote from provider responses rather than from any constant. Three induced failures each recovered: no wallet installed, wrong network (4902 then addEthereumChain then switch), and a rejected signature (EIP-1193 4001) | evidence/phase9/connect.md, ui-v2/src/lib/wallet.ts | bash scripts/130-connect-flow.sh | DEMONSTRATED | 9.1 | $D |
| C-901 | The landing surface is the FIRST tab and the default, so a cold visitor is already on it and the click count starts at zero. Zero blocking empty states, zero text overlaps, zero horizontal overflow, and the primary action's bounding rect fully inside the viewport at both 1280x720 and 390x844, with a one-sentence value proposition present at both | evidence/phase9/landing.md | bash scripts/131-landing-audit.sh | DEMONSTRATED | 9.2 | $D |
| C-902 | A user who touches nothing runs under limits identical to Limits::conservative, proved as a three-way equality after a real UI-driven activation: the Rust crate WRITES ui-v2/public/data/limits.json, the screen renders 25 tQUOTE from it, and AgentVault.maxNotional reads 25000000000000000000 on chain. The crate is included because a TypeScript constant would let the engine change while the screen and the chain still agreed with each other and both were wrong | evidence/phase9/defaults.md | bash scripts/132-defaults-audit.sh | DEMONSTRATED | 9.3 | $D |
| C-903 | Deposit and activate is THREE interactions from a genuinely cold wallet: one app click, one EIP-712 signature, one transaction confirmation, each listed individually by an instrumented capturing listener that also wraps the provider so wallet prompts are counted. Cold state asserted on chain first (allowance 0, balance 0, permit nonce 0), because the measurement read ONE click twice on warm accounts and both readings were true of that account and false of every first visitor | evidence/phase9/click-count.md, docs/decisions/ADR-017-permit-for-a-three-click-activation.md | bash scripts/133-click-count.sh | DEMONSTRATED | 9.4 | $D |
| C-904 | Pause and Withdraw are present, inside the viewport and confirmed reachable by an elementFromPoint hit test on all five routes at both 1280x720 and 390x844, ten route-and-viewport combinations. The hit test is what distinguishes visible from merely positioned: a control under an overlay passes every geometric check and is unclickable | evidence/phase9/exit-controls.md, ui-v2/src/components/exit-bar.tsx | bash scripts/134-exit-controls-audit.sh | DEMONSTRATED | 9.5 | $D |
| C-905 | One button runs a complete live cycle with no deposit and no wallet: ten consecutive runs, ten successes, each writing a NEW journal row in a NEW block, slowest 17.6s. Every run showed thesis, risk verdict, execution and a decoded FeeCharged event; the fee on tx 0x6e6d290cc9dafe3a74e78bb60ddc9faf42cd912fd47eb7ba2f1cf3935266c500 decodes to 14250000000000000 on a notional of 2850000000000000000 at 50 bps, arithmetic checked | evidence/phase9/demo-button.md | bash scripts/135-demo-button.sh | DEMONSTRATED | 9.6 | $D |
| C-906 | The personal dashboard shows real data 11ms after route load against a 1000ms budget, and zero tracked fields render a bare zero while their source is still loading: the activation control is a tri-state that disables itself and reads "Reading your position..." when the chain read has not returned, so a loading state can never be mistaken for a real zero balance | evidence/phase9/dashboard.md | bash scripts/137-dashboard-audit.sh | DEMONSTRATED | 9.7 | $D |
| C-907 | Five induced failures produce five recoverable states and zero dead ends, each naming its specific cause AND its specific next action, each verified to recover after the cause is removed: rejected signature, wrong chain, RPC outage, insufficient balance and pause during an in-flight deposit. Contract reverts are decoded rather than dumped, so a raw 0xcf479181 now reads "You asked to withdraw 1000000.0000 tQUOTE but only 50.0000 is available right now" | evidence/phase9/failure-paths.md, ui-v2/src/lib/revert.ts | bash scripts/138-failure-paths.sh | DEMONSTRATED | 9.8 | $D |
| C-908 | The fee is disclosed before activation in basis points and in plain words, read live from FeeCollector.feeBps(). Proved by more than a grep: the rate was LOWERED on chain from 50 to 49 and the UI followed, with the chain read independently in the same check rather than trusting the UI's own claim. No hardcoded fee rate exists anywhere in ui-v2/src | evidence/phase9/fee-disclosure.md | bash scripts/139-fee-disclosure.sh | DEMONSTRATED | 9.9 | $D |
| C-909 | The frontend gate passes at desktop viewports: zero of fourteen components uncited, zero characters below WCAG AA with a worst ratio of 8.28:1 against a 4.5:1 floor across all five views, zero clipping containers and zero collapsed cells at 1920x1080, and 53 controls double-clicked in sequence without a crash or a blank. The four Phase 4 views clip at 390x844, measured by the project's own Phase 4 gate and scoped as a known defect by ADR-018 rather than resolved | evidence/phase9/phase9-redteam.md, docs/decisions/ADR-018-mobile-layout-deferred.md | bash scripts/140-phase9-redteam.sh | DEMONSTRATED | 9.10 | $D |
MD

echo "rows now: $(grep -c '^| C-' "$CoE")"
