#!/usr/bin/env bash
set -uo pipefail
cd "$(dirname "$0")"
. ./lib.sh
D=$(date -u '+%Y-%m-%d')
cat >> "$REPO/evidence/CHAIN-OF-EVIDENCE.md" <<MD
| C-1100 | Chain 196 verified live: eth_chainId returns 0xc4, gas price 20,000,001 wei read from eth_gasPrice, gas token OKB with 18 decimals established by arithmetic rather than from a page, and the judge-facing explorer LOADED in a real browser with its page title recorded. That load found the URL form had changed: oklink.com/x-layer/address redirects to oklink.com/x-layer/evm/address, which curl -L follows silently while reporting 200 for the old form | docs/verified/chain-196-reality.md | bash scripts/146-mainnet-facts.sh | DEMONSTRATED | 11.1 | $D |
| C-1101 | Every gas cost in the mainnet plan measured on testnet first, each row labelled RECEIPT or ESTIMATE because mixing the two silently is how a budget goes wrong in the direction that matters: agent cycle 255,459 and depositWithPermit 146,682 from real receipts, withdrawAll 52,842 and postOrder 170,404 from live estimates against the deployment | evidence/phase11/gas-inventory.md | bash scripts/147-gas-inventory.sh | DEMONSTRATED | 11.2 | $D |
| C-1102 | The exact mainnet requirement is 0.000473160 OKB, being 7,886,001 gas at a live 20,000,001 wei with a stated 3x margin, and the deployment half is MEASURED by cast estimate --create against chain 196 rather than modelled: the original 200-gas-per-byte model was 12.3 percent high and was replaced by the measurement rather than the tolerance being widened | evidence/phase11/budget.md | bash scripts/148-mainnet-budget.sh | DEMONSTRATED | 11.3 | $D |
| C-1103 | The full deployment was rehearsed against chain 196 in estimate-only mode, asserting eth_chainId equals 196 before any estimate ran, and agrees with the budget to 0.0 percent because the dry run READS the budget's output rather than carrying a copy of it. Zero spend proven by the chain rather than asserted: nonce unchanged at 0 and balance unchanged at 5000000000000000 wei, with no keystore or password argument anywhere in the script | evidence/phase11/dryrun.txt | bash scripts/149-mainnet-dryrun.sh | DEMONSTRATED | 11.4 | $D |
| C-1104 | A 17-step deployment order derived from the constructors in the source rather than recalled, with a stated recovery action for every step, an explicit note that immutable constructor arguments mean a wrong address forces a redeploy rather than a reconfiguration, and the one step where retry is the wrong instinct named: a hold from the risk engine is the system refusing correctly, not a failure to force past | evidence/phase11/deploy-plan.md | bash scripts/151-deploy-plan.sh | DEMONSTRATED | 11.5 | $D |
| C-1105 | Exchange OS has no usable developer surface reachable on mainnet, established four ways per R-SEARCH-2: okx.com returns 000 DNS non-resolution, oklink and xlayerscan resolve but expose no address, the CHAIN ITSELF holds 7 contracts with code of which 5 are OP Stack system contracts, 2 are WOKB and Multicall3 and 0 are exchange primitives, and a real browser render found nothing further. The SELF-DEPLOYED STAND-IN labels therefore stay exactly as they are | docs/verified/exchangeos-mainnet.md | bash scripts/150d-call-discovered.sh | DEMONSTRATED | 11.6 | $D |
| C-1106 | Chain 196 reverse engineered from primary onchain evidence: 12 contracts fetched and hashed, five OP Stack predeploys found to share BYTE-IDENTICAL runtime code which identified them as proxies, EIP-1967 implementation slots computed rather than pasted and followed to five distinct implementations, selectors extracted from the implementation dispatch tables and identified by computing keccak256 locally so each match is arithmetic, then every discovered function CALLED. DEMONSTRATED: OP Stack, past Ecotone and Fjord with GasPriceOracle v1.6.0, L2StandardBridge v1.13.0. This FORCED A CORRECTION to CLAUDE.md, whose AggLayer settlement claim is not visible in the bytecode at all and is now labelled INFERRED | docs/verified/onchain-reverse-engineering-196.md, evidence/phase11/bytecode/ | bash scripts/150-reverse-engineer-196.sh | DEMONSTRATED | 11.7 | $D |
MD
echo "rows now: $(grep -c '^| C-' "$REPO/evidence/CHAIN-OF-EVIDENCE.md")"
