#!/usr/bin/env bash
set -uo pipefail
cd "$(dirname "$0")"
. ./lib.sh
D=$(date -u '+%Y-%m-%d')
cat >> "$REPO/evidence/CHAIN-OF-EVIDENCE.md" <<MD
| C-1200 | Seven contracts deployed to X Layer MAINNET chain 196 in the dependency order derived from their constructors, and every address had its runtime code read back with eth_getCode before success was reported, because a deploy transaction that succeeds and leaves no code is a thing that happens. The fee treasury is deliberately NOT the deployer, since task 7.6 found that treasury equals maker equals deployer makes fee revenue and trade proceeds indistinguishable | docs/verified/deployments-mainnet.md, deployments-mainnet.json | bash scripts/153-mainnet-deploy.sh | DEMONSTRATED | 12.1 | $D |
| C-1201 | A complete agent loop on mainnet at block 68099407: the runtime read the live book, found 12 resting orders, generated and scored 25 candidates, formed the thesis BOOK IS CROSSED best bid 1.900000 is at or above best ask 1.700000 so spread-based inference is unreliable, passed the winner through the risk gate and submitted tx 0xb4785fbcbd2ba5f007b5735c63ee671aa178547da066bceb6ae0bef75bbcec6f with status 0x1, with a journal row naming that same hash | evidence/phase12/mainnet-loop.md | bash scripts/154-mainnet-loop.sh | DEMONSTRATED | 12.2 | $D |
| C-1202 | An explicit risk refusal on mainnet, produced three independent ways so no single artifact carries the claim: a SUBMITTED transaction 0x6a0237847f4d73794b56b3083f0603e91e831cfd3cf20281f8665ec63c83e48e that reverted with status 0x0 at mainnet block 68100752, a simulated call returning the decoded custom error ExceedsUserLimit(2000000000000000000, 1000000000000000000), and the offchain engine refusing to construct RiskApproved across 43 passing tests. Chain id and mainnet block number are on every artifact because this task's fake win is captioning a testnet refusal as mainnet | evidence/phase12/mainnet-refusal.md | bash scripts/155-mainnet-refusal.sh | DEMONSTRATED | 12.3 | $D |
| C-1203 | A live fee event on mainnet, decoded from eth_getTransactionReceipt and not from local state: feeAmount 14250000000000000 on a notional of 2850000000000000000 at 50 bps, with the arithmetic checked, and cross-checked against contract state showing the treasury holding exactly that balance and fee.chargeCount() equal to 1. The treasury is not the deployer, so the balance is fee revenue and nothing else | evidence/phase12/mainnet-fee.md | bash scripts/156-mainnet-fee.sh | DEMONSTRATED | 12.4 | $D |
| C-1204 | A real user deposit, an agent action under a real per-user limit, and a full withdrawal, all on mainnet across five transactions, leaving the vault solvent with the user's vault balance at zero. The restoration assertion FIRED on a minus 2 aQUOTE wallet delta and the tokens were followed rather than the number rounded away: closeTrade pulls from msg.sender and on this deployment the agent and the user are one address, so one wallet funded both sides while the proceeds rest at the venue. The user's deposit was fully restored, 5 in and 5 out | evidence/phase12/mainnet-personal.md | bash scripts/157-mainnet-personal.sh | DEMONSTRATED | 12.5 | $D |
| C-1205 | The entire mainnet launch cost 203651990182599 wei, 0.000203652 OKB, across 75 transactions, reconciled against the deployer's balance delta rather than summed from a table of plausible figures. NO USD FIGURE IS ASSERTED: the chain cannot be asked what OKB is worth and no price oracle is trusted for a documentation line, so a table across prices is given instead, which is this task's named fake win refused rather than committed | evidence/phase12/mainnet-cost.md | bash scripts/158-mainnet-cost.sh | DEMONSTRATED | 12.6 | $D |
| C-1206 | Every mainnet hash is one click from the dashboard: 17 transaction anchors and 7 contract anchors, each carrying a resolvable href and opening in a new tab, generated from a manifest that SCRAPES hashes out of the Phase 12 evidence files so no hash can appear that no document recorded. Loading a real transaction URL in a browser found that the tx explorer form redirects exactly as the address form did, which curl -L follows silently while reporting 200, so both are now the post-redirect canonical form | evidence/phase12/mainnet-discoverability.txt, ui-v2/src/components/mainnet-panel.tsx | bash scripts/159-mainnet-manifest.sh | DEMONSTRATED | 12.7 | $D |
MD
echo "rows now: $(grep -c '^| C-' "$REPO/evidence/CHAIN-OF-EVIDENCE.md")"
