"""Task 16.4: the fake-win register, checked.

THINKING: #66 red teaming, #7 is-this-real, #49 evidence.

TASKS.md names, for many subtasks, "the specific way this task could look green while proving
nothing". This builds the register from those declarations and asks, for each: is there a claim in
the chain covering that task, and does that claim's text actually SAY how the fake win was refused?

WHAT THIS CAN AND CANNOT CHECK, because the difference decides how much the output is worth. It can
check that a named fake win has a corresponding claim, and it can surface the claim so a reader can
judge the refusal for themselves. It CANNOT decide whether a refusal is convincing: that is a
judgement, and a script that pretended to make it would itself be the fake win for this task. So the
register prints the pairing and the human-checkable text, and reports coverage, not correctness.
"""
import json
import os
import re
import sys

REPO = "/mnt/c/Users/zulab/OneDrive/Desktop/ASML-X"
TASKS = f"{REPO}/TASKS.md"
CHAIN = f"{REPO}/evidence/CHAIN-OF-EVIDENCE.md"
OUT = f"{REPO}/evidence/phase16/fake-win-register.md"


def fake_wins():
    """Each FAKE WIN line, attributed to the nearest preceding task number."""
    out = []
    task = None
    for line in open(TASKS, encoding="utf-8"):
        m = re.match(r"^#{0,3}\s*\**(\d+\.\d+)\**", line.strip())
        if m:
            task = m.group(1)
        m2 = re.match(r"^\s*FAKE WIN:\s*(.+)$", line.strip())
        if m2 and task:
            text = m2.group(1).strip()
            # The template line in the header is a description of the field, not a real one.
            if "the specific way this task could look green" in text:
                continue
            out.append((task, text))
    return out


def claims():
    rows = {}
    for line in open(CHAIN, encoding="utf-8"):
        if not line.startswith("| C-"):
            continue
        p = [x.strip() for x in line.split("|")]
        if len(p) < 8:
            continue
        rows.setdefault(p[6], []).append({"id": p[1], "claim": p[2], "evidence": p[3]})
    return rows


def main():
    fw = fake_wins()
    cl = claims()

    covered, uncovered = [], []
    for task, text in fw:
        if task in cl:
            covered.append((task, text, cl[task]))
        else:
            uncovered.append((task, text))

    L = []
    w = L.append
    w("# Task 16.4: the fake-win register, checked")
    w("")
    w(f"{len(fw)} fake wins are named in TASKS.md. **{len(covered)} have a claim in the evidence")
    w(f"chain for that subtask; {len(uncovered)} do not.**")
    w("")
    w("## What this register can and cannot tell you")
    w("")
    w("It checks that every named fake win has a claim covering its subtask, and it prints the claim")
    w("so a reader can judge the refusal themselves.")
    w("")
    w("**It cannot decide whether a refusal is convincing.** That is a judgement, and a script that")
    w("pretended to make it would itself be this task's fake win: a green tick asserting that thirty")
    w("traps were avoided, generated by the same process that might have fallen into them. So what")
    w("follows reports COVERAGE and shows the text. Correctness is left where it belongs.")
    w("")
    if uncovered:
        w("## Fake wins with NO claim for their subtask")
        w("")
        w("| task | the fake win |")
        w("|---|---|")
        for t, x in uncovered:
            w(f"| {t} | {x} |")
        w("")
    w("## The register")
    w("")
    for task, text, rows in covered:
        w(f"### {task}")
        w("")
        w(f"**Fake win:** {text}")
        w("")
        for r in rows:
            w(f"**{r['id']}** — {r['claim'][:520]}{'...' if len(r['claim']) > 520 else ''}")
            w("")
            w(f"Evidence: `{r['evidence']}`")
            w("")

    w("## Reproduce")
    w("")
    w("```")
    w("python3 scripts/185-fake-win-register.py")
    w("```")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")

    print(f"fake wins named:   {len(fw)}")
    print(f"with a claim:      {len(covered)}")
    print(f"without a claim:   {len(uncovered)}")
    for t, x in uncovered:
        print(f"   {t}  {x[:70]}")
    print(f"written: {OUT}")
    return 0 if not uncovered else 1


if __name__ == "__main__":
    sys.exit(main())
