"""Rewrite the UI's contract manifest to the LOCAL chain's deployment, for the browser job.

WHY. The failure-path audit reads `data/deployments.json` to find AgentVault and then sends a real
`withdraw` through the provider. Those two must agree on the chain: with the manifest naming testnet
contracts and the provider on a local chain, the read fails; with the manifest on testnet and the
signer holding an unfunded throwaway key, gas estimation fails with "gas required exceeds allowance
(0)" before the contract ever reverts, so the audit never sees InsufficientBalance.

Pointing everything at the local chain fixes both: the contracts exist, the key can be funded
freely, and the vault returns the real revert the audit is testing for.

This writes to `ui-v2/dist/data/` only, which is BUILD OUTPUT and gitignored. The tracked manifest
under `ui-v2/public/data/` is left alone, so nothing about the real deployment record changes.
"""
import json
import os
import shutil
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SRC_MANIFEST = os.path.join(REPO, "ui-v2", "public", "data", "deployments.json")
DIST_DIR = os.path.join(REPO, "ui-v2", "dist", "data")
# Prefer the snapshot scripts/197 leaves behind, because 197 RESTORES deployments.json to the real
# testnet record on exit and the local addresses would otherwise be gone by the time this runs.
DEPLOY = (
    "/tmp/asml-ci-deployments.json"
    if os.path.exists("/tmp/asml-ci-deployments.json")
    else os.path.join(REPO, "deployments.json")
)

# Manifest name -> key in deployments.json
NAME_TO_KEY = {
    "MockERC20 tBASE": "tBASE",
    "MockERC20 tQUOTE": "tQUOTE",
    "OrderBookVenue": "venue",
    "RiskGuard": "riskGuard",
    "BatchExecutor": "batchExecutor",
    "FeeCollector": "feeCollector",
    "AgentVault": "agentVault",
}


def main():
    local = json.load(open(DEPLOY, encoding="utf-8"))
    if "127.0.0.1" not in str(local.get("rpc", "")):
        print(f"deployments.json does not describe a local chain (rpc={local.get('rpc')}). Refusing.")
        return 1

    manifest = json.load(open(SRC_MANIFEST, encoding="utf-8"))
    manifest["chain_id"] = local["chainId"]
    manifest["rpc_url"] = local["rpc"]
    manifest["source"] = "generated by scripts/201-ci-ui-manifest-local.py for the CI browser job"

    missing = []
    for entry in manifest["deployments"]:
        key = NAME_TO_KEY.get(entry["name"])
        if key is None:
            continue
        if key not in local:
            missing.append(entry["name"])
            continue
        entry["address"] = local[key]

    if missing:
        print(f"local deployment is missing: {missing}. Refusing to write a half-correct manifest.")
        return 1

    os.makedirs(DIST_DIR, exist_ok=True)
    out = os.path.join(DIST_DIR, "deployments.json")
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(manifest, fh, indent=2)

    print(f"wrote {out}")
    print(f"  chain_id {manifest['chain_id']}  rpc {manifest['rpc_url']}")
    for e in manifest["deployments"]:
        print(f"  {e['name']:22} {e['address']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
